echo Tạo môi trường ảo...
python -m venv venv

echo Kích hoạt môi trường ảo...
call venv\Scripts\activate

echo Cài đặt các thư viện cần thiết...
pip install -r requirements.txt

echo Cài đặt Flask...
pip install flask

echo Cấu hình biến môi trường cho Flask...
set FLASK_APP=flaskr

echo Khởi tạo database...
flask --app flaskr init-db

echo Chạy ứng dụng Flask...
flask --app flaskr run --debug
